org: sziben
app: monday-automations
service: monday-update-multiplier
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  region: eu-central-1
  stage: ${opt:stage, 'dev'}

  # Define the resource policy
  apiGateway:
    resourcePolicy:
      - Effect: "Allow"
        Principal: "*"
        Action: "execute-api:Invoke"
        Resource:
          - "execute-api:/*/*/*"
        Condition:
          IpAddress:
            aws:SourceIp:
              - "82.115.214.0/24"
              - "185.66.202.0/23"
              - "185.237.4.0/22"

functions:
  mondayUpdateMultiplier:
    handler: lambda_handler.lambda_handler
    environment: ${file(env.json)}
    timeout: 15
    memorySize: 128
    events:
      - http:
          path: /monday-gateway
          method: any
    layers:
      - Ref: PythonRequirementsLambdaLayer
custom:
  pythonRequirements:
    layer: true

plugins:
  - serverless-python-requirements
